export const REDIS_MODULE_CONNECTION = 'IO_REDIS_CONNECTION';
export const REDIS_MODULE_CONNECTION_TOKEN = 'IO_REDIS_CONNECTION_TOKEN';

export const REDIS_MODULE_OPTIONS_TOKEN = 'IO_REDIS_OPTIONS_TOKEN';

export const PRIMARY_KEY_METADATA_KEY = 'REDIS:PK';
export const REDIS_ENTITY_METADATA_KEY = 'REDIS:REDIS_ENTITY';
